### ISSUE TITLE
[BUG] CUDA compilation failure after cudf submodule update: deleted default constructor of rmm::detail::view_holder

### ISSUE THREAD

**Issue by hyperbolic2346** [NVIDIA/spark-rapids-jni#4027]
**Describe the bug**
Build: spark-rapids-jni_submodule-sync-dev/5617

The build fails during CUDA compilation of libcudf after updating the cudf submodule from e88a42e5abd0 to 0446f87b81. Multiple source files fail to compile with the error: "the default constructor of 'rmm::detail::view_holder' cannot be referenced -- it is a deleted function" at rmm/detail/cccl_adaptors.hpp:206.

The error occurs in two cudf source files:
1. src/binaryop/compiled/binary_ops.cu
2. src/labeling/label_bins.cu

Both fail when attempting to construct device_scalar objects that internally use pinned host vectors with RMM allocators. The compilation error chain shows the issue originates from rmm::detail::cccl_async_resource_ref trying to default-construct view_holder{}, which now has a deleted default constructor.

Error logs:
```
[124/727] Building CUDA object CMakeFiles/cudf.dir/src/binaryop/compiled/binary_ops.cu.o
FAILED: CMakeFiles/cudf.dir/src/binaryop/compiled/binary_ops.cu.o
rmm/detail/cccl_adaptors.hpp(206): error: the default constructor of "rmm::detail::view_holder" cannot be referenced -- it is a deleted function
    cccl_async_resource_ref(ResourceType&& ref) : view_holder{}, base{std::move(ref)} {}
1 error detected in the compilation

[128/727] Building CUDA object CMakeFiles/cudf.dir/src/labeling/label_bins.cu.o
FAILED: Same error as above
```

**Environment details**
- CUDA: 12.9.86
- Compiler: GCC 14.2.1
- Build system: CMake 3.30.4 with Ninja
- Cudf commit: 0446f87b81a26789a6d87aeabe2206a7abfc51e3
