### ISSUE TITLE
[BUG] failed to build JNI with latest kvikIO compat mode change

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids-jni#2609]
**Describe the bug**
submodule sync and cudf JNI build failed after https://github.com/rapidsai/kvikio/pull/547
```
[2024-11-20T03:15:49.612Z] [INFO]      [exec] /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-3978/thirdparty/cudf/cpp/src/io/utilities/config_utils.cpp: In lambda function:

[2024-11-20T03:15:49.613Z] [INFO]      [exec] /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-3978/thirdparty/cudf/cpp/src/io/utilities/config_utils.cpp:60:41: error: cannot convert 'const bool' to 'kvikio::CompatMode'

[2024-11-20T03:15:49.613Z] [INFO]      [exec]    60 |     kvikio::defaults::compat_mode_reset(compat_mode);

[2024-11-20T03:15:49.613Z] [INFO]      [exec]       |                                         ^~~~~~~~~~~

[2024-11-20T03:15:49.613Z] [INFO]      [exec]       |                                         |

[2024-11-20T03:15:49.613Z] [INFO]      [exec]       |                                         const bool

[2024-11-20T03:15:49.613Z] [INFO]      [exec] In file included from /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-3978/thirdparty/cudf/cpp/src/io/utilities/config_utils.cpp:21:

[2024-11-20T03:15:49.613Z] [INFO]      [exec] /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-3978/target/libcudf/cmake-build/_deps/kvikio-src/cpp/include/kvikio/defaults.hpp:226:44: note:   initializing argument 1 of 'static void kvikio::defaults::compat_mode_reset(kvikio::CompatMode)'

[2024-11-20T03:15:49.613Z] [INFO]      [exec]   226 |   static void compat_mode_reset(CompatMode compat_mode) { instance()->_compat_mode = compat_mode; }

[2024-11-20T03:15:49.613Z] [INFO]      [exec]       |                                 ~~~~~~~~~~~^~~~~~~~~~~

[2024-11-20T03:15:49.868Z] [INFO]      [exec] [ 58%] Building CXX object CMakeFiles/cudf.dir/src/io/utilities/data_sink.cpp.o
```

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by jlowe** [comment]
submodule sync is working again after the libcudf fix.
